import { Component } from '@angular/core';
import { Config } from 'datatables.net';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Sapph';
  dtoptions :Config={};
  users:any=[
    {
        "UserID": 7,
        "FirstName": "rahul",
        "LastName": "PAWAR",
        "Email": "rahul@gmail.com",
        "Password": "g3QmX9g0LCqTUrJ1volL5jCSZGsK5hIolVnbeJ3w1vXdDagJ8MFo1g==",
        "RoleID": 1,
        "ClientID": 37,
        "IsActive": true,
        "CreatedBy": null,
        "Created_Date": "2024-08-14T12:39:39.103",
        "ModifiedBy": 1,
        "ModifyDate": "2024-08-14T17:39:31.257",
        "RoleID1": 1,
        "RoleName": "Admin",
        "CreatedBy1": 1,
        "Created_Date1": "2024-08-07T15:28:06.567",
        "ModifiedBy1": null,
        "ModifyDate1": null,
        "ClientID1": 37,
        "ClientName": "Niket",
        "ClientTypeID": 1,
        "ParentClientID": 0,
        "IndustryID": 0,
        "Email1": "pawarniket123@gmail.com",
        "Address": "pallanji ratanji chawl no 9 patra ahes dk marg byculla mumbai 400027",
        "City": "Mumbai",
        "State": 14,
        "Country": 1,
        "Pincode": "400027",
        "GSTNo": "989525252",
        "Regulated": "RBI / MAS / SAMA",
        "Certified": "ISO / NIST",
        "ContactPerson_name": "DEEPAK",
        "ContactPerson_designation": null,
        "ContactPerson_mobile": null,
        "IsActive1": true,
        "CreatedBy2": null,
        "Created_Date2": null,
        "ModifiedBy2": null,
        "ModifyDate2": null
    },
    {
        "UserID": 8,
        "FirstName": "deva",
        "LastName": "pawar",
        "Email": "deva@gmail.com",
        "Password": "15151",
        "RoleID": 1,
        "ClientID": 9,
        "IsActive": true,
        "CreatedBy": null,
        "Created_Date": "2024-08-14T15:57:05.97",
        "ModifiedBy": null,
        "ModifyDate": null,
        "RoleID1": 1,
        "RoleName": "Admin",
        "CreatedBy1": 1,
        "Created_Date1": "2024-08-07T15:28:06.567",
        "ModifiedBy1": null,
        "ModifyDate1": null,
        "ClientID1": 9,
        "ClientName": "Vijay wakle",
        "ClientTypeID": 1,
        "ParentClientID": null,
        "IndustryID": null,
        "Email1": "vijay@gmail.com",
        "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
        "City": "Kalwa, Thane",
        "State": 14,
        "Country": 1,
        "Pincode": "400605",
        "GSTNo": "123",
        "Regulated": null,
        "Certified": null,
        "ContactPerson_name": "fghj",
        "ContactPerson_designation": null,
        "ContactPerson_mobile": null,
        "IsActive1": true,
        "CreatedBy2": null,
        "Created_Date2": null,
        "ModifiedBy2": null,
        "ModifyDate2": null
    },
    {
        "UserID": 11,
        "FirstName": "Jheel",
        "LastName": "Bhavsar",
        "Email": "jheel.bhavsar4@gmail.com",
        "Password": "12345",
        "RoleID": 3,
        "ClientID": 7,
        "IsActive": true,
        "CreatedBy": null,
        "Created_Date": "2024-08-14T17:03:44.687",
        "ModifiedBy": null,
        "ModifyDate": null,
        "RoleID1": 3,
        "RoleName": "Approver",
        "CreatedBy1": 1,
        "Created_Date1": "2024-08-07T15:28:06.567",
        "ModifiedBy1": null,
        "ModifyDate1": null,
        "ClientID1": 7,
        "ClientName": "Vijay wakle 2",
        "ClientTypeID": 2,
        "ParentClientID": null,
        "IndustryID": null,
        "Email1": "vijay@gmail.com",
        "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
        "City": "Kalwa, Thane",
        "State": 14,
        "Country": 1,
        "Pincode": "400600",
        "GSTNo": "1234",
        "Regulated": null,
        "Certified": null,
        "ContactPerson_name": "Vijay wakle",
        "ContactPerson_designation": null,
        "ContactPerson_mobile": null,
        "IsActive1": true,
        "CreatedBy2": null,
        "Created_Date2": null,
        "ModifiedBy2": null,
        "ModifyDate2": null
    },
    {
        "UserID": 12,
        "FirstName": "Vijay",
        "LastName": "wakle",
        "Email": "vijay@gmail.com",
        "Password": "12345",
        "RoleID": 1,
        "ClientID": 7,
        "IsActive": true,
        "CreatedBy": null,
        "Created_Date": "2024-08-16T11:45:21.173",
        "ModifiedBy": null,
        "ModifyDate": null,
        "RoleID1": 1,
        "RoleName": "Admin",
        "CreatedBy1": 1,
        "Created_Date1": "2024-08-07T15:28:06.567",
        "ModifiedBy1": null,
        "ModifyDate1": null,
        "ClientID1": 7,
        "ClientName": "Vijay wakle 2",
        "ClientTypeID": 2,
        "ParentClientID": null,
        "IndustryID": null,
        "Email1": "vijay@gmail.com",
        "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
        "City": "Kalwa, Thane",
        "State": 14,
        "Country": 1,
        "Pincode": "400600",
        "GSTNo": "1234",
        "Regulated": null,
        "Certified": null,
        "ContactPerson_name": "Vijay wakle",
        "ContactPerson_designation": null,
        "ContactPerson_mobile": null,
        "IsActive1": true,
        "CreatedBy2": null,
        "Created_Date2": null,
        "ModifiedBy2": null,
        "ModifyDate2": null
    },
    {
      "UserID": 12,
      "FirstName": "Vijay",
      "LastName": "wakle",
      "Email": "vijay@gmail.com",
      "Password": "12345",
      "RoleID": 1,
      "ClientID": 7,
      "IsActive": true,
      "CreatedBy": null,
      "Created_Date": "2024-08-16T11:45:21.173",
      "ModifiedBy": null,
      "ModifyDate": null,
      "RoleID1": 1,
      "RoleName": "Admin",
      "CreatedBy1": 1,
      "Created_Date1": "2024-08-07T15:28:06.567",
      "ModifiedBy1": null,
      "ModifyDate1": null,
      "ClientID1": 7,
      "ClientName": "Vijay wakle 2",
      "ClientTypeID": 2,
      "ParentClientID": null,
      "IndustryID": null,
      "Email1": "vijay@gmail.com",
      "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
      "City": "Kalwa, Thane",
      "State": 14,
      "Country": 1,
      "Pincode": "400600",
      "GSTNo": "1234",
      "Regulated": null,
      "Certified": null,
      "ContactPerson_name": "Vijay wakle",
      "ContactPerson_designation": null,
      "ContactPerson_mobile": null,
      "IsActive1": true,
      "CreatedBy2": null,
      "Created_Date2": null,
      "ModifiedBy2": null,
      "ModifyDate2": null
  },
  {
    "UserID": 12,
    "FirstName": "Vijay",
    "LastName": "wakle",
    "Email": "vijay@gmail.com",
    "Password": "12345",
    "RoleID": 1,
    "ClientID": 7,
    "IsActive": true,
    "CreatedBy": null,
    "Created_Date": "2024-08-16T11:45:21.173",
    "ModifiedBy": null,
    "ModifyDate": null,
    "RoleID1": 1,
    "RoleName": "Admin",
    "CreatedBy1": 1,
    "Created_Date1": "2024-08-07T15:28:06.567",
    "ModifiedBy1": null,
    "ModifyDate1": null,
    "ClientID1": 7,
    "ClientName": "Vijay wakle 2",
    "ClientTypeID": 2,
    "ParentClientID": null,
    "IndustryID": null,
    "Email1": "vijay@gmail.com",
    "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
    "City": "Kalwa, Thane",
    "State": 14,
    "Country": 1,
    "Pincode": "400600",
    "GSTNo": "1234",
    "Regulated": null,
    "Certified": null,
    "ContactPerson_name": "Vijay wakle",
    "ContactPerson_designation": null,
    "ContactPerson_mobile": null,
    "IsActive1": true,
    "CreatedBy2": null,
    "Created_Date2": null,
    "ModifiedBy2": null,
    "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
},
{
  "UserID": 12,
  "FirstName": "Vijay",
  "LastName": "wakle",
  "Email": "vijay@gmail.com",
  "Password": "12345",
  "RoleID": 1,
  "ClientID": 7,
  "IsActive": true,
  "CreatedBy": null,
  "Created_Date": "2024-08-16T11:45:21.173",
  "ModifiedBy": null,
  "ModifyDate": null,
  "RoleID1": 1,
  "RoleName": "Admin",
  "CreatedBy1": 1,
  "Created_Date1": "2024-08-07T15:28:06.567",
  "ModifiedBy1": null,
  "ModifyDate1": null,
  "ClientID1": 7,
  "ClientName": "Vijay wakle 2",
  "ClientTypeID": 2,
  "ParentClientID": null,
  "IndustryID": null,
  "Email1": "vijay@gmail.com",
  "Address": "Room no. 2 chawl no. 19, Janaki nagar manisha nagar kalwa (w)",
  "City": "Kalwa, Thane",
  "State": 14,
  "Country": 1,
  "Pincode": "400600",
  "GSTNo": "1234",
  "Regulated": null,
  "Certified": null,
  "ContactPerson_name": "Vijay wakle",
  "ContactPerson_designation": null,
  "ContactPerson_mobile": null,
  "IsActive1": true,
  "CreatedBy2": null,
  "Created_Date2": null,
  "ModifiedBy2": null,
  "ModifyDate2": null
}
]
}
